import turtle

def turtleLetter(letter,tur):
    if letter=="box":
        tur.setheading(0)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)
        tur.right(90)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)

    elif letter == "A":
        tur.setheading(0)
        tur.pu()
        tur.fd(10)
        tur.right(90)
        tur.fd(10)
        tur.pd()
        tur.fd(40)
        tur.right(180)
        tur.fd(40)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(40)
        tur.right(180)
        tur.fd(20)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        #fixes
        tur.right(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(30)
        #tur.right(180)
        
    elif letter == "B":
        tur.pu()
        tur.fd(10)
        tur.right(90)
        tur.fd(10)
        tur.pd()
        tur.fd(40)
        tur.left(90)
        tur.fd(20)
        tur.left(90)
        tur.fd(20)
        tur.left(90)
        tur.fd(20)
        tur.right(180)
        tur.fd(20)
        tur.left(90)
        tur.fd(20)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        tur.right(180)
        tur.fd(30)
        tur.left(90)
        tur.fd(10)
        tur.right(90)
		
    elif letter == "C":
        tur.pu()
        tur.fd(10)
        tur.right(90)
        tur.fd(10)
        tur.pd()
        tur.left(90)
        tur.fd(20)
        tur.right(180)
        tur.fd(20)
        tur.left(90)
        tur.fd(40)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        tur.fd(10)
        tur.left(90)
        tur.fd(50)
        tur.right(90)
        
    elif letter == "D":
        tur.pu()
        tur.fd(10)
        tur.right(90)
        tur.fd(10)
        tur.pd()
        tur.fd(40)
        tur.left(112.5)
        tur.fd(30)
        tur.left(67.5)
        tur.fd(20)
        tur.left(71)
        tur.fd(30)
        tur.pu()
        tur.right(161)
        tur.fd(30)
        tur.left(90)
        tur.fd(10)
        tur.right(90)

    elif letter == "E":
        tur.pu()
        tur.fd(10)
        tur.right(90)
        tur.fd(10)
        tur.pd()
        tur.fd(40)
        tur.left(90)
        tur.fd(20)
        tur.right(180)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.right(180)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.pu()
        tur.fd(10)
        tur.left(90)
        tur.fd(10)
        tur.right(90)

    elif letter == "F":
        tur.pu()
        tur.fd(10)
        tur.right(90)
        tur.fd(10)
        tur.pd()
        tur.fd(40)
        tur.right(180)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.right(180)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.pu()
        tur.fd(10)
        tur.left(90)
        tur.fd(10)
        tur.right(90)
	
    elif letter == "G":
	tur.pd()
	tur.forward(30)
	tur.right(180)
	tur.forward(30)
	tur.left(90)
	tur.forward(60)
	tur.left(90)
	tur.forward(30)
	tur.left(90)
	tur.forward(20)
	tur.left(90)
	tur.forward(20)
	tur.right(180)
	tur.forward(20)
	tur.right(90)
	tur.forward(20)
	tur.right(90)
	tur.forward(30)
	tur.right(90)
	tur.forward(60)
	tur.right(90)
	tur.forward(30)
	tur.pu()
	tur.forward(5)
	tur.pd()
	 
    elif letter == "H":
	tur.pd()
	tur.right(90)
	tur.forward(60)
	tur.right(180)
	tur.forward(30)
	tur.right(90)
	tur.forward(30)
	tur.left(90)
	tur.forward(30)
	tur.right(180)
	tur.forward(60)
	tur.pu()
	tur.right(180)
	tur.forward(60)
	tur.right(90)
	tur.forward(10)
	tur.pd()
	  
  
    elif letter == "I":
	tur.pd()
	tur.forward(30)
	tur.right(180)
	tur.forward(15)
	tur.left(90)
	tur.forward(60)
	tur.left(90)
	tur.forward(15)
	tur.left(180)
	tur.forward(30)
	tur.left(180)
	tur.forward(15)
	tur.left(90)
	tur.forward(60)
	tur.right(90)
	tur.forward(15)
	tur.pu()
	tur.forward(5)
	tur.pd()


	    
    elif letter == "J":
	tur.pd()
	tur.forward(30)
	tur.right(180)
	tur.forward(10)
	tur.left(90)
	tur.forward(60)
	tur.right(90)
	tur.forward(20)
	tur.right(90)
	tur.forward(15)
	tur.pu()
	tur.forward(45)
	tur.right(90)
	tur.forward(40)
	tur.pd()

	    
    elif letter == "K":
	tur.pd()
	tur.right(90)
	tur.forward(60)
	tur.right(180)
	tur.forward(30)
	tur.right(45)
	tur.forward(40)
	tur.right(180)
	tur.forward(40)
	tur.left(90)
	tur.forward(40)
	tur.pu()
	tur.left(135)
	tur.forward(60)
	tur.right(90)
	tur.forward(5)
	tur.pd()

    elif letter == "L":
	tur.setheading(0)
	tur.pd()
	tur.right(90)
	tur.fd(60)
	tur.left(90)
	tur.fd(40)
	tur.pu()
	tur.right(-90)
	tur.fd(60)
	tur.right(90)	
    elif letter == "M":
	tur.pu()
        tur.right(90)
        tur.fd(60)
        tur.left(90)
        tur.fd(10)
        tur.pd()
        tur.left(90)
        tur.fd(60)
        tur.right(130)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.right(130)
        tur.fd(60)
        tur.pu()
        tur.right(180)
        tur.fd(60)
        tur.right(90)
        tur.fd(10)

    elif letter == "N":
	tur.pu()
        tur.right(90)
        tur.fd(60)
        tur.right(-90)
        tur.pd()
        tur.left(90)
        tur.fd(60)
        tur.right(130)
        tur.fd(60)
        tur.left(130)
        tur.fd(60)
        tur.pu()
        tur.right(90)
        tur.fd(10)
    elif letter == "O":
	tur.pu()
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.pd()
        tur.circle(35, 360)
        tur.pu()
        tur.fd(20)
        tur.right(-90)
        tur.fd(65)
        tur.right(90)
        tur.fd(15)
        tur.pu()
        tur.right(180)
        tur.fd(65)
        tur.right(90)
        tur.fd(10)
    elif letter == "P":
	tur.pu()
        tur.right(90)
        tur.fd(20)
        tur.left(90)
        tur.pd()
        tur.circle(15, 180)
        tur.left(90)
        tur.fd(60)
        tur.pu()
        tur.right(-90)
        tur.fd(30)
        tur.right(-90)
        tur.fd(60)
        tur.right(90)
    elif letter == "Q":
	tur.setheading(0)
	tur.pu()
	tur.fd(5)
	tur.right(90)
	tur.fd(5)
	tur.pd()
	tur.fd(40)
	tur.left(90)
	tur.fd(30)
	tur.right(45)
	tur.fd(10)
	tur.bk(10)
	tur.right(-135)
	tur.fd(40)
	tur.right(270)
	tur.fd(30)
	tur.pu()
	tur.right(180)
	tur.fd(40)
	tur.pu()
	tur.right(0)
    elif letter == "R":
	tur.setheading(0)
	tur.pu()
	tur.fd(5)
	tur.right(90)
	tur.fd(5)
	tur.pd()
	tur.fd(40)
	tur.bk(40)
	tur.left(90)
	tur.fd(30)
	tur.right(90)
	tur.fd(20)
	tur.right(90)
	tur.fd(20)
	tur.right(-135)
	tur.fd(30)
	tur.pu()
	tur.right(-135)
	tur.fd(50)
	tur.right(90)
    elif letter == "S":
	tur.setheading(0)
	tur.pu()
	tur.fd(5)
	tur.pd()
	tur.fd(35)
	tur.bk(35)
	tur.right(90)
	tur.fd(25)
	tur.right(270)
	tur.fd(35)
	tur.right(90)
	tur.fd(25)
	tur.right(-270)
	tur.fd(35)
	tur.pu()
	tur.right(180)
	tur.fd(50)
	tur.right(-90)
	tur.fd(50)
	tur.right(90)
    elif letter == "T":
	tur.setheading(0)
	tur.pu()
	tur.fd(5)
	tur.pd()
	tur.fd(35)
	tur.bk(17.5)
	tur.right(90)
	tur.fd(50)
	tur.pu()
	tur.right(-90)
	tur.fd(20)
	tur.right(-90)
	tur.fd(55)
	tur.right(90)
    elif letter == "U":
	tur.pd()
        tur.right(90)
        tur.fd(80)
        tur.right(-45)
        tur.fd(20)
        tur.right(-45)
        tur.fd(40)
        tur.right(-45)
        tur.fd(20)
        tur.right(-45)
        tur.fd(80)
	tur.pu()
	tur.right(90)
	tur.fd(7)
    elif letter == "V":
	tur.setheading(0)
	tur.pu()
	tur.fd(5)
	tur.right(45)
	tur.fd(5)
	tur.pd()
	tur.fd(30)
	tur.right(270)
	tur.fd(30)
	tur.pu()
	tur.right(90)
    elif letter == "W":
	tur.pd()
        tur.right(70)
        tur.fd(80)
        tur.right(-140)
        tur.fd(40)
        tur.right(90)
        tur.fd(40)
        tur.right(-140)
        tur.fd(80)
	tur.pu()
	tur.right(90)
	tur.fd(7)
    elif letter == "X":
        tur.pd()
        tur.right(45)
	tur.fd(80)
	tur.right(-180)
	tur.fd(40)
	tur.right(90)
	tur.fd(40)
	tur.right(180)
	tur.fd(80)
	tur.pu()
	tur.right(180)
	tur.fd(80)
	tur.right(45)
	tur.fd(10)
    elif letter == "Y":
	tur.right(45)
	tur.fd(30)
	tur.right(-90)
	tur.fd(30)
	tur.right(-180)
	tur.fd(30)
	tur.right(-45)
	tur.fd(40)
	tur.pu()
	tur.left(90)
	tur.forward(20)
	tur.left(90)
	tur.forward(60)
	tur.right(90)
	tur.pd()
        
    elif letter == "Z":
	tur.pd()
	tur.forward(30)
	tur.left(245)
	tur.forward(70)
	tur.left(115)
	tur.forward(30)
 
	    		

        
    elif letter == "Ax":
        # code here
        tur.forward(40)
		
    else:
        turtleLetter("box",tur)
	
2






window = turtle.Screen()
tur = turtle.Turtle()
tur.speed(1)
#turtleLetter("box",tur)
turtleLetter("A",tur)


window.exitonclick()
